import type { RegistryComponent } from "./types.js";

export const COMPONENTS: RegistryComponent[] = [
  {
    name: "button",
    description: "Primary action button with 4 variants and loading state",
    category: "primitives",
    files: ["primitives/button.tsx"],
    deps: ["class-variance-authority", "lucide-react", "@radix-ui/react-slot"],
    registryDeps: [],
  },
  {
    name: "badge",
    description: "Status badge — solid/soft/outline × 6 semantic colors",
    category: "primitives",
    files: ["primitives/badge.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "input",
    description: "Text input with default, search, and command (⌘K) variants",
    category: "primitives",
    files: ["primitives/input.tsx"],
    deps: ["class-variance-authority", "lucide-react"],
    registryDeps: [],
  },
  {
    name: "card",
    description: "Content card — default/featured/terminal/data variants",
    category: "primitives",
    files: ["primitives/card.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "dialog",
    description: "Modal dialog built on Radix UI with accessible close button",
    category: "primitives",
    files: ["primitives/dialog.tsx"],
    deps: ["@radix-ui/react-dialog", "lucide-react"],
    registryDeps: [],
  },
  {
    name: "dropdown",
    description: "Dropdown menu with items, checkboxes, radio groups and submenus",
    category: "primitives",
    files: ["primitives/dropdown.tsx"],
    deps: ["@radix-ui/react-dropdown-menu", "lucide-react"],
    registryDeps: [],
  },
  {
    name: "tooltip",
    description: "Hover tooltip with optional keyboard shortcut hint",
    category: "primitives",
    files: ["primitives/tooltip.tsx"],
    deps: ["@radix-ui/react-tooltip"],
    registryDeps: [],
  },
  {
    name: "tabs",
    description: "Editor-style file tabs with optional close button and icon",
    category: "primitives",
    files: ["primitives/tabs.tsx"],
    deps: ["@radix-ui/react-tabs", "lucide-react"],
    registryDeps: [],
  },
  {
    name: "tab-bar",
    description: "Full-width IDE editor tab bar with diamond logo and closeable tabs",
    category: "layout",
    files: ["layout/tab-bar.tsx"],
    deps: ["lucide-react"],
    registryDeps: [],
  },
  {
    name: "status-bar",
    description: "Fixed bottom status bar with brand color and left/right sections",
    category: "layout",
    files: ["layout/status-bar.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "top-nav",
    description: "Horizontal nav bar with logo, breadcrumb, and actions slots",
    category: "layout",
    files: ["layout/top-nav.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "section-header",
    description: "Eyebrow label + two-color headline for landing page sections",
    category: "layout",
    files: ["layout/section-header.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "skeleton",
    description: "Animated shimmer placeholder for loading states",
    category: "feedback",
    files: ["feedback/skeleton.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "toast",
    description: "Toast notifications via Sonner, styled with entrepta tokens",
    category: "feedback",
    files: ["feedback/toast.tsx"],
    deps: ["sonner"],
    registryDeps: [],
  },
  {
    name: "command-palette",
    description: "⌘K command palette built on cmdk with groups, icons, and shortcuts",
    category: "feedback",
    files: ["feedback/command-palette.tsx"],
    deps: ["cmdk", "@radix-ui/react-dialog", "lucide-react"],
    registryDeps: [],
  },
];
