/**
 * Every installable item in the registry: what the CLI copies and installs, and
 * what the docs site lists. One source, so the two cannot drift.
 */

/**
 * The folders components live in. In a user project they all land in one
 * folder, so an import from one to another becomes a sibling import; the CLI
 * and the docs build that rewrite from this list.
 */
export const COMPONENT_FOLDERS = [
  "primitives",
  "layout",
  "content",
  "feedback",
  "motion",
  "data",
  "charts",
] as const;

export type RegistryCategory = (typeof COMPONENT_FOLDERS)[number] | "hooks" | "lib";

export interface RegistryComponent {
  name: string;
  description: string;
  category: RegistryCategory;
  files: string[];
  deps: string[];
  registryDeps: string[];
  /** One line of JSX showing the component in use. Every component has one; hooks and lib files do not. */
  usage?: string;
  /** What its own files export, for import lines. Checked against the files by a test. */
  exports?: string[];
}

export const COMPONENTS: RegistryComponent[] = [
  {
    name: "button",
    description: "Primary action button with 4 variants, icon sizes and a loading state",
    category: "primitives",
    files: ["primitives/button.tsx", "primitives/button-variants.ts"],
    deps: ["class-variance-authority", "@phosphor-icons/react", "@radix-ui/react-slot"],
    registryDeps: [],
    usage: `<Button variant="primary" size="md">ship it</Button>`,
    exports: ["Button", "buttonVariants"],
  },
  {
    name: "badge",
    description: "Status badge, solid/soft/outline across 6 semantic colors, with a dot or an icon",
    category: "primitives",
    files: ["primitives/badge.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["icon-lib"],
    usage: `<Badge variant="soft" color="success" dot>shipped</Badge>`,
    exports: ["Badge", "badgeVariants"],
  },
  {
    name: "avatar",
    description:
      "A person or a thing as an image over its initials, with a presence dot and a stacked group",
    category: "primitives",
    files: ["primitives/avatar.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["icon-lib"],
    usage: `<Avatar name="Anna Maria" src="/me.jpg" status="online" />`,
    exports: ["Avatar", "AvatarGroup", "avatarVariants"],
  },
  {
    name: "input",
    description: "Text input with default, search, and command (⌘K) variants",
    category: "primitives",
    files: ["primitives/input.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["kbd"],
    usage: `<Input variant="search" placeholder="search…" />`,
    exports: ["Input", "fieldTrigger", "inputFieldClass", "inputWrapperVariants"],
  },
  {
    name: "card",
    description: "Content card, default/featured/terminal/data variants in three sizes",
    category: "primitives",
    files: ["primitives/card.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["diamond", "icon-lib"],
    usage:
      "<Card><CardHeader><CardLabel>post</CardLabel><CardMeta>2026</CardMeta></CardHeader><CardTitle>Title</CardTitle></Card>",
    exports: [
      "Card",
      "cardVariants",
      "CardHeader",
      "CardLabel",
      "CardMeta",
      "CardTitle",
      "CardDescription",
      "CardContent",
      "CardFooter",
      "CardComment",
      "CardTerminalBar",
      "CardTerminalBody",
    ],
  },
  {
    name: "dialog",
    description: "Modal dialog built on Radix UI with accessible close button",
    category: "primitives",
    files: ["primitives/dialog.tsx"],
    deps: ["@radix-ui/react-dialog", "@phosphor-icons/react"],
    registryDeps: ["diamond", "overlay-lib", "icon-lib"],
    usage:
      "<Dialog><DialogTrigger asChild><Button>open</Button></DialogTrigger><DialogContent><DialogTitle>Title</DialogTitle></DialogContent></Dialog>",
    exports: [
      "Dialog",
      "DialogClose",
      "DialogCloseButton",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogLabel",
      "DialogOverlay",
      "DialogPortal",
      "DialogTitle",
      "DialogTrigger",
    ],
  },
  {
    name: "money-input",
    description:
      "Money typed like a cash machine or freely, pasted in any format, held in minor units",
    category: "primitives",
    files: ["primitives/money-input.tsx"],
    deps: [],
    registryDeps: ["input", "use-format", "format-lib"],
    usage: '<MoneyInput currency="EUR" value={minor} onValueChange={setMinor} size="lg" />',
    exports: ["MoneyInput"],
  },
  {
    name: "icon-tile",
    description:
      "An icon in a tinted square, for a category, an account or a status, with a corner badge",
    category: "primitives",
    files: ["primitives/icon-tile.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["icon-lib"],
    usage: '<IconTile icon={ForkKnifeIcon} color="chart-3" />',
    exports: ["IconTile", "iconTileVariants"],
  },
  {
    name: "delta",
    description:
      "How a value moved: an arrow, a sign and the change, colored by whether that is good news",
    category: "data",
    files: ["data/delta.tsx"],
    deps: ["@phosphor-icons/react", "class-variance-authority"],
    registryDeps: ["tooltip", "use-format", "format-lib"],
    usage: '<Delta current={spent} previous={lastMonth} intent="increase-is-bad" />',
    exports: ["Delta", "compareValues", "deltaVariants"],
  },
  {
    name: "sparkline",
    description:
      "The shape of a series with no axes, wiping in once on screen, for a Metric's trend",
    category: "data",
    files: ["data/sparkline.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib", "palette-lib"],
    usage: '<Sparkline data={last30Days} tone="chart-1" />',
    exports: ["Sparkline"],
  },
  {
    name: "bar-list",
    description: "A ranking in rows, each label in full on a bar as long as its share; server safe",
    category: "data",
    files: ["data/bar-list.tsx"],
    deps: [],
    registryDeps: ["amount", "palette-lib", "format-lib"],
    usage: '<BarList items={categories} max={5} showOthers format="money" />',
    exports: ["BarList"],
  },
  {
    name: "chart",
    description:
      "The frame for Recharts: palette colors, a tooltip in full values, a legend from three series, the data as a table",
    category: "charts",
    files: ["charts/chart.tsx"],
    deps: ["recharts", "@phosphor-icons/react"],
    registryDeps: [
      "amount",
      "table",
      "button",
      "use-format",
      "format-lib",
      "overlay-lib",
      "palette-lib",
    ],
    usage:
      '<ChartContainer config={config} height={240} label="Spending by month" data={rows} categoryKey="month"><AreaChart data={rows}>…</AreaChart></ChartContainer>',
    exports: [
      "ChartContainer",
      "ChartTooltip",
      "ChartTooltipContent",
      "ChartLegend",
      "ChartLegendContent",
      "chartColor",
      "chartCursor",
      "chartGrid",
      "chartGridHorizontal",
      "chartMargin",
      "chartProjection",
      "chartTick",
      "chartXAxis",
      "chartYAxis",
      "formatChartValue",
      "useChartConfig",
      "useChartMotion",
    ],
  },
  {
    name: "redact",
    description:
      "A value hidden behind a mask of its width when the app asks, read as hidden value",
    category: "data",
    files: ["data/redact.tsx"],
    deps: [],
    registryDeps: ["use-redact"],
    usage: "<RedactProvider hidden={hide}><Redact>{accountNumber}</Redact></RedactProvider>",
    exports: ["Redact"],
  },
  {
    name: "contribution-grid",
    description:
      "A year of days as weeks, levels from the brand, one Tab stop walked by the arrows",
    category: "data",
    files: ["data/contribution-grid.tsx"],
    deps: [],
    registryDeps: ["skeleton", "use-format", "format-lib", "overlay-lib"],
    usage: '<ContributionGrid label="Workouts this year" days={days} onSelect={openDay} />',
    exports: ["ContributionGrid"],
  },
  {
    name: "metric",
    description: "One number with its label, how it moved and against what; loads in its own shape",
    category: "data",
    files: ["data/metric.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: ["diamond", "skeleton", "icon-lib", "redact"],
    usage:
      '<Metric label="spent" value={<Amount value={spent} />} delta={<Delta current={spent} previous={last} />} comparison="vs August" />',
    exports: ["Metric"],
  },
  {
    name: "list-row",
    description:
      "The standard row of a list, with a leading tile, a truncating title and a trailing value",
    category: "data",
    files: ["data/list-row.tsx"],
    deps: [],
    registryDeps: [],
    usage:
      '<ListGroup label="Today"><ListRow leading={…} title="Coffee" meta="card" trailing={<Amount … />} /></ListGroup>',
    exports: ["ListGroup", "ListRow"],
  },
  {
    name: "table",
    description:
      "A real table that scrolls in its own box, with a sticky header and numbers on the right",
    category: "data",
    files: ["data/table.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage:
      "<Table><TableHeader><TableRow><TableHead>item</TableHead></TableRow></TableHeader><TableBody>…</TableBody></Table>",
    exports: [
      "Table",
      "TableBody",
      "TableCaption",
      "TableCell",
      "TableFooter",
      "TableHead",
      "TableHeader",
      "TableRow",
      "cellVariants",
    ],
  },
  {
    name: "data-table",
    description:
      "Records to sort, select and hide columns in, on TanStack Table, virtualized past 500 rows",
    category: "data",
    files: ["data/data-table.tsx"],
    deps: ["@tanstack/react-table", "@tanstack/react-virtual", "@phosphor-icons/react"],
    registryDeps: ["table", "checkbox", "skeleton", "empty-state", "button"],
    usage:
      '<DataTable aria-label="entries" data={rows} columns={columns} numeric={["amount"]} selectable />',
    exports: ["DataTable", "dataTableColumns", "dataTableFeatures"],
  },
  {
    name: "filter-builder",
    description:
      "Filters built from fields, each one an applied pill, kept in the URL with serializeFilters",
    category: "data",
    files: ["data/filter-builder.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: [
      "filters-lib",
      "filter-pill",
      "popover",
      "segmented-control",
      "combobox",
      "input",
      "money-input",
      "calendar",
      "button",
      "use-format",
      "format-lib",
      "icon-lib",
      "overlay-lib",
    ],
    usage: "<FilterBuilder fields={FIELDS} value={filters} onValueChange={setFilters} />",
    exports: ["FilterBuilder"],
  },
  {
    name: "empty-state",
    description: "A list or a widget with nothing in it: what is missing, and the one thing to do",
    category: "feedback",
    files: ["feedback/empty-state.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: ["icon-tile"],
    usage:
      '<EmptyState icon={TrayIcon} title="No entries this month" action={<Button>add</Button>} />',
    exports: ["EmptyState", "emptyStateVariants"],
  },
  {
    name: "alert",
    description:
      "A notice that stays until it is dealt with, its status in a tile and the corner glow",
    category: "feedback",
    files: ["feedback/alert.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["icon-tile", "overlay-lib"],
    usage: '<Alert tone="warning" title="Partial data">Two accounts have not synced today.</Alert>',
    exports: ["Alert", "alertVariants"],
  },
  {
    name: "amount",
    description: "Money shown one way everywhere: mono, tabular, the real minus, a muted symbol",
    category: "data",
    files: ["data/amount.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: ["use-format", "format-lib", "redact"],
    usage: '<Amount value={-4500} currency="EUR" tone="auto" />',
    exports: ["Amount", "amountVariants"],
  },
  {
    name: "select",
    description: "A value from a short list, in a form, with the field's look and the menu's rows",
    category: "primitives",
    files: ["primitives/select.tsx"],
    deps: ["@radix-ui/react-select", "@phosphor-icons/react"],
    registryDeps: ["input", "overlay-lib"],
    usage:
      '<Select><SelectTrigger><SelectValue placeholder="Pick one…" /></SelectTrigger><SelectContent><SelectItem value="a">a</SelectItem></SelectContent></Select>',
    exports: [
      "Select",
      "SelectContent",
      "SelectGroup",
      "SelectItem",
      "SelectLabel",
      "SelectSeparator",
      "SelectTrigger",
      "SelectValue",
    ],
  },
  {
    name: "combobox",
    description:
      "A value from a long list you can search: groups, several values, create on the spot",
    category: "primitives",
    files: ["primitives/combobox.tsx"],
    deps: ["cmdk", "@phosphor-icons/react"],
    registryDeps: ["command-palette", "popover", "badge", "input"],
    usage: "<Combobox options={zones} value={zone} onValueChange={setZone} />",
    exports: ["Combobox"],
  },
  {
    name: "segmented-control",
    description: "One choice out of a few, all in view, on native radios with a sliding indicator",
    category: "primitives",
    files: ["primitives/segmented-control.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["icon-lib"],
    usage:
      '<SegmentedControl aria-label="kind" options={kinds} value={kind} onValueChange={setKind} />',
    exports: ["SegmentedControl"],
  },
  {
    name: "calendar",
    description:
      "A month of days to pick a day or a range from, in plain dates, on react-day-picker",
    category: "primitives",
    files: ["primitives/calendar.tsx"],
    deps: ["react-day-picker", "@phosphor-icons/react"],
    registryDeps: ["use-format", "format-lib"],
    usage: '<Calendar value={day} onValueChange={setDay} timeZone="America/Sao_Paulo" />',
    exports: ["Calendar", "calendarNavButton"],
  },
  {
    name: "date-picker",
    description: "A day, a range, a month or a year, picked from a calendar in a popover",
    category: "primitives",
    files: ["primitives/date-picker.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["calendar", "popover", "input", "overlay-lib", "use-format", "format-lib"],
    usage: "<DatePicker value={day} onValueChange={setDay} />",
    exports: ["DatePicker"],
  },
  {
    name: "date-navigator",
    description: "Previous, the period, next and today, to walk through days, months or years",
    category: "primitives",
    files: ["primitives/date-navigator.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["date-picker", "button", "tooltip", "use-format", "format-lib"],
    usage: '<DateNavigator aria-label="day" value={day} onValueChange={setDay} max={today} />',
    exports: ["DateNavigator"],
  },
  {
    name: "popover",
    description: "A panel anchored to a trigger, for content you work in: a calendar, a filter",
    category: "primitives",
    files: ["primitives/popover.tsx"],
    deps: ["@radix-ui/react-popover"],
    registryDeps: ["overlay-lib"],
    usage:
      '<Popover><PopoverTrigger asChild><Button>filters</Button></PopoverTrigger><PopoverContent aria-label="Filters">…</PopoverContent></Popover>',
    exports: ["Popover", "PopoverAnchor", "PopoverClose", "PopoverContent", "PopoverTrigger"],
  },
  {
    name: "sheet",
    description:
      "A panel from the edge to create or edit without leaving the list, that asks before losing changes",
    category: "primitives",
    files: ["primitives/sheet.tsx"],
    deps: ["@radix-ui/react-dialog", "class-variance-authority"],
    registryDeps: ["dialog", "button", "overlay-lib"],
    usage:
      '<Sheet dirty={dirty}><SheetTrigger asChild><Button>new</Button></SheetTrigger><SheetContent title="New entry" footer={…}>…</SheetContent></Sheet>',
    exports: ["Sheet", "SheetClose", "SheetContent", "SheetTrigger", "sheetVariants"],
  },
  {
    name: "progress",
    description:
      "How far along: a bar, a bar in steps or a ring, as a progressbar with its value in words",
    category: "primitives",
    files: ["primitives/progress.tsx"],
    deps: ["class-variance-authority", "motion"],
    registryDeps: ["motion-lib"],
    usage: '<Progress label="budget" value={spent} max={budget} showValue />',
    exports: ["Progress"],
  },
  {
    name: "accordion",
    description:
      "Sections that open in place, with a trailing value in the header and actions beside it",
    category: "primitives",
    files: ["primitives/accordion.tsx"],
    deps: ["@radix-ui/react-accordion", "@phosphor-icons/react"],
    registryDeps: [],
    usage:
      '<Accordion type="single" collapsible><AccordionItem value="home"><AccordionTrigger trailing={<Amount value={total} />}>home</AccordionTrigger><AccordionContent>…</AccordionContent></AccordionItem></Accordion>',
    exports: ["Accordion", "AccordionContent", "AccordionItem", "AccordionTrigger"],
  },
  {
    name: "stepper",
    description: "Where someone is in a flow: an ordered list, the current step with the diamond",
    category: "primitives",
    files: ["primitives/stepper.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["diamond"],
    usage: '<Stepper steps={STEPS} current="bank" />',
    exports: ["Stepper"],
  },
  {
    name: "choice-card",
    description:
      "A choice that needs more than a word: cards that are labels of native radios or checkboxes",
    category: "primitives",
    files: ["primitives/choice-card.tsx"],
    deps: [],
    registryDeps: ["card", "icon-tile", "icon-lib", "field", "diamond"],
    usage: '<ChoiceCard legend="Plan" options={PLANS} value={plan} onValueChange={setPlan} />',
    exports: ["ChoiceCard"],
  },
  {
    name: "secret-field",
    description:
      "A secret to copy once: masked, revealed on request, copied with a polite confirmation",
    category: "primitives",
    files: ["primitives/secret-field.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["input", "button", "use-copy"],
    usage: '<SecretField name="API key" value={key} />',
    exports: ["SecretField", "maskSecret"],
  },
  {
    name: "swatch-picker",
    description:
      "A palette color by key, never a hex: native radios, each swatch named after its hue",
    category: "primitives",
    files: ["primitives/swatch-picker.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["palette-lib", "field", "diamond"],
    usage: '<SwatchPicker legend="Color" value={color} onValueChange={setColor} />',
    exports: ["SwatchPicker"],
  },
  {
    name: "file-dropzone",
    description:
      "A real file input to drop on or choose from, checking type and size, listing progress",
    category: "primitives",
    files: ["primitives/file-dropzone.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["button", "icon-tile", "progress", "use-format"],
    usage:
      '<FileDropzone accept="image/*" maxSize={5_000_000} multiple onFiles={upload} items={uploads} />',
    exports: ["FileDropzone", "accepts", "formatBytes"],
  },
  {
    name: "prompt-input",
    description:
      "Where a question is written: grows, sends on Cmd Enter, stops while streaming, suggestions",
    category: "primitives",
    files: ["primitives/prompt-input.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["button", "kbd"],
    usage:
      "<PromptInput onSubmit={send} streaming={busy} onStop={stop} suggestions={SUGGESTIONS} />",
    exports: ["PromptInput"],
  },
  {
    name: "dropdown",
    description: "Dropdown menu with items, checkboxes, radio groups and submenus",
    category: "primitives",
    files: ["primitives/dropdown.tsx"],
    deps: ["@radix-ui/react-dropdown-menu", "@phosphor-icons/react"],
    registryDeps: ["kbd", "overlay-lib"],
    usage:
      "<DropdownMenu><DropdownMenuTrigger asChild><Button>menu</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>item</DropdownMenuItem></DropdownMenuContent></DropdownMenu>",
    exports: [
      "DropdownMenu",
      "DropdownMenuCheckboxItem",
      "DropdownMenuContent",
      "DropdownMenuDestructiveItem",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuLabel",
      "DropdownMenuPortal",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuTrigger",
    ],
  },
  {
    name: "tooltip",
    description: "Hover tooltip with optional keyboard shortcut hint",
    category: "primitives",
    files: ["primitives/tooltip.tsx"],
    deps: ["@radix-ui/react-tooltip"],
    registryDeps: ["kbd", "overlay-lib"],
    usage:
      "<Tooltip><TooltipTrigger asChild><Button>save</Button></TooltipTrigger><TooltipContent>save <TooltipShortcut>⌘S</TooltipShortcut></TooltipContent></Tooltip>",
    exports: ["Tooltip", "TooltipContent", "TooltipProvider", "TooltipShortcut", "TooltipTrigger"],
  },
  {
    name: "tabs",
    description:
      "Editor file tabs, in place or as routes, with a travelling underline, a close button and a title bar variant",
    category: "primitives",
    files: ["primitives/tabs.tsx"],
    deps: ["@radix-ui/react-tabs", "@radix-ui/react-slot", "@phosphor-icons/react", "motion"],
    registryDeps: ["diamond", "motion-lib"],
    usage: `<Tabs defaultValue="a"><TabsList><TabsTrigger value="a">a.tsx</TabsTrigger></TabsList><TabsContent value="a">…</TabsContent></Tabs>`,
    exports: ["TabNav", "TabNavLink", "Tabs", "TabsContent", "TabsList", "TabsTrigger"],
  },
  {
    name: "status-bar",
    description: "Bottom status bar in the brand color, fixed or in your layout",
    category: "layout",
    files: ["layout/status-bar.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage:
      "<StatusBar left={<StatusBarItem>main</StatusBarItem>} right={<StatusBarItem>UTF-8</StatusBarItem>} />",
    exports: ["StatusBar", "StatusBarItem", "StatusBarSeparator", "statusBarVariants"],
  },
  {
    name: "top-nav",
    description: "Horizontal nav bar with logo, breadcrumb, and actions slots",
    category: "layout",
    files: ["layout/top-nav.tsx"],
    deps: [],
    registryDeps: [],
    usage: "<TopNav left={<TopNavLogo>…</TopNavLogo>} right={…} />",
    exports: [
      "TopNav",
      "TopNavBreadcrumb",
      "TopNavLink",
      "TopNavLogo",
      "TopNavLogoMark",
      "TopNavMenu",
      "TopNavSeparator",
    ],
  },
  {
    name: "skeleton",
    description: "Animated shimmer placeholder for loading states",
    category: "feedback",
    files: ["feedback/skeleton.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<Skeleton variant="line" delay={i * 0.06} />`,
    exports: ["Skeleton", "SkeletonText"],
  },
  {
    name: "toast",
    description: "Toast notifications via Sonner, styled with entrepta tokens",
    category: "feedback",
    files: ["feedback/toast.tsx"],
    deps: ["sonner", "@phosphor-icons/react"],
    registryDeps: ["overlay-lib", "icon-tile"],
    usage: `<Toaster /> then toast.success("saved")`,
    exports: ["Toaster", "toast"],
  },
  {
    name: "use-command-palette",
    description: "Hook that wires the ⌘K global shortcut to open/close the command palette",
    category: "hooks",
    files: ["hooks/use-command-palette.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-redact",
    description: "RedactProvider and useRedacted: the app's switch to hide values on screen",
    category: "hooks",
    files: ["hooks/use-redact.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-copy",
    description: "Hook that copies text and reports copied or failed, then settles back",
    category: "hooks",
    files: ["hooks/use-copy.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-format",
    description:
      "FormatProvider and useFormat: the locale, currency and time zone formatting reads",
    category: "hooks",
    files: ["hooks/use-format.ts"],
    deps: [],
    registryDeps: ["format-lib"],
  },
  {
    name: "use-mode",
    description: "Hook that manages dark/light mode with localStorage persistence",
    category: "hooks",
    files: ["hooks/use-mode.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-theme",
    description: "Hook that manages theme + dark/light mode with localStorage persistence",
    category: "hooks",
    files: ["hooks/use-theme.ts"],
    deps: [],
    registryDeps: ["use-mode"],
  },
  {
    name: "theme-switcher",
    description: "Floating theme + mode picker with no-flash ThemeScript helper",
    category: "layout",
    files: ["layout/theme-switcher.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-theme", "overlay-lib"],
    usage: "<ThemeSwitcher themes={THEMES} /> with <ThemeScript /> in <head>",
    exports: ["ThemeScript", "ThemeSwitcher"],
  },
  {
    name: "mode-toggle",
    description: "Dark/light only toggle, inline or floating, with no-flash ModeScript helper",
    category: "layout",
    files: ["layout/mode-toggle.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["use-mode"],
    usage: "<ModeToggle /> with <ModeScript /> in <head>",
    exports: ["ModeScript", "ModeToggle"],
  },
  {
    name: "command-palette",
    description: "⌘K command palette built on cmdk with groups, icons, and shortcuts",
    category: "feedback",
    files: ["feedback/command-palette.tsx"],
    deps: ["cmdk", "@radix-ui/react-dialog", "@phosphor-icons/react"],
    registryDeps: ["use-command-palette", "kbd", "overlay-lib"],
    usage:
      "<CommandDialog open={open} onOpenChange={setOpen}><Command><CommandInput /><CommandList>…</CommandList></Command></CommandDialog>",
    exports: [
      "Command",
      "CommandDialog",
      "CommandEmpty",
      "CommandFoot",
      "CommandGroup",
      "CommandInput",
      "CommandItem",
      "CommandList",
      "CommandSeparator",
    ],
  },
  {
    name: "diamond",
    description: "The ◆ brand mark placed before a label, hidden from screen readers",
    category: "content",
    files: ["content/diamond.tsx"],
    deps: [],
    registryDeps: [],
    usage: "<Diamond size={10} />",
    exports: ["Diamond"],
  },
  {
    name: "chat-thread",
    description: "A conversation by role, tool results in cards, streaming that keeps your place",
    category: "content",
    files: ["content/chat-thread.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["button", "card", "diamond", "overlay-lib"],
    usage: '<ChatThread messages={messages} className="h-[560px]" />',
    exports: ["ChatThread"],
  },
  {
    name: "code-block",
    description: "Code container with macOS chrome, language label and a copy-to-clipboard button",
    category: "content",
    files: ["content/code-block.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-copy"],
    usage: `<CodeBlock code="npm run dev" language="bash" variant="terminal" />`,
    exports: ["CodeBlock"],
  },
  {
    name: "icon-lib",
    description: "An icon prop that takes a Phosphor component or an element",
    category: "lib",
    files: ["lib/icon.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: [],
  },
  {
    name: "overlay-lib",
    description: "The shared overlay surface, menu row, label and separator classes",
    category: "lib",
    files: ["lib/overlay.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "motion-lib",
    description: "Shared motion values: the ease-out curve, the viewport rule and the stagger cap",
    category: "lib",
    files: ["lib/motion.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "filters-lib",
    description: "Filter types, URL serializing and parsing checked against the fields, matching",
    category: "lib",
    files: ["lib/filters.ts"],
    deps: [],
    registryDeps: ["format-lib"],
  },
  {
    name: "nav-lib",
    description: "The classes of a nav row, current and idle, shared by every list of destinations",
    category: "lib",
    files: ["lib/nav.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "palette-lib",
    description: "The series colors by name: the eight palette colors and the statuses",
    category: "lib",
    files: ["lib/palette.ts"],
    deps: [],
    registryDeps: ["color-contrast"],
  },
  {
    name: "format-lib",
    description: "Money in minor units, numbers and plain dates, formatted and parsed with Intl",
    category: "lib",
    files: ["lib/format.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "color-contrast",
    description: "WCAG contrast math: parse colors, flatten translucent layers, measure the ratio",
    category: "lib",
    files: ["lib/color-contrast.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "reveal",
    description: "Entrance that rises and fades in once on screen, with a capped list stagger",
    category: "motion",
    files: ["motion/reveal.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
    usage: "<Reveal index={i}><Card>…</Card></Reveal>",
    exports: ["Reveal", "useReveal"],
  },
  {
    name: "type-in",
    description: "Text that assembles piece by piece, with the full sentence always in the DOM",
    category: "motion",
    files: ["motion/type-in.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
    usage: `<TypeIn as="h1" text="Build with entrepta." emphasis="entrepta" />`,
    exports: ["TypeIn"],
  },
  {
    name: "rolling-number",
    description: "Odometer counter that rolls into place and turns once on hover",
    category: "motion",
    files: ["motion/rolling-number.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib", "redact"],
    usage: "<RollingNumber value={128} height={44} />",
    exports: ["RollingNumber", "useRollOnHover"],
  },
  {
    name: "spotlight",
    description: "Brand glow that trails the cursor across a card on a spring",
    category: "motion",
    files: ["motion/spotlight.tsx"],
    deps: ["motion"],
    registryDeps: [],
    usage:
      "const { onMouseMove, spotlight } = useSpotlight(); <Card onMouseMove={onMouseMove}><Spotlight {...spotlight} />…</Card>",
    exports: ["Spotlight", "useSpotlight"],
  },
  {
    name: "spotlight-card",
    description: "A Card with the brand glow trailing the cursor, usable from a server page",
    category: "motion",
    files: ["motion/spotlight-card.tsx"],
    deps: ["motion"],
    registryDeps: ["card", "spotlight"],
    usage: '<SpotlightCard variant="featured"><CardTitle>…</CardTitle></SpotlightCard>',
    exports: ["SpotlightCard"],
  },
  {
    name: "arrow-link",
    description: "Text link with a traveling arrow and a brand rule that wipes in",
    category: "motion",
    files: ["motion/arrow-link.tsx"],
    deps: ["@phosphor-icons/react", "@radix-ui/react-slot"],
    registryDeps: [],
    usage: `<ArrowLink href="/docs">read the docs</ArrowLink>`,
    exports: ["ArrowAffordance", "ArrowLink"],
  },
  {
    name: "switch",
    description: "On/off switch over a native checkbox, with an optional label",
    category: "primitives",
    files: ["primitives/switch.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<Switch label="notifications" />`,
    exports: ["Switch"],
  },
  {
    name: "kbd",
    description: "A key or a shortcut, as a chip or plain, that turns brand in a highlighted row",
    category: "primitives",
    files: ["primitives/kbd.tsx"],
    deps: [],
    registryDeps: [],
    usage: "<Kbd>⌘K</Kbd>",
    exports: ["Kbd"],
  },
  {
    name: "checkbox",
    description: "Checkbox over a native input, with a label, a description and a mixed state",
    category: "primitives",
    files: ["primitives/checkbox.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<Checkbox label="button" description="4 variants" defaultChecked />`,
    exports: ["Checkbox"],
  },
  {
    name: "textarea",
    description: "Multi-line text field in sans, with an error state",
    category: "primitives",
    files: ["primitives/textarea.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage: `<Textarea placeholder="// your message" />`,
    exports: ["Textarea", "textareaVariants"],
  },
  {
    name: "field",
    description: "Label, control and error or hint, wired together for screen readers",
    category: "primitives",
    files: ["primitives/field.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["diamond", "icon-lib"],
    usage: '<Field id="email" label="email" error={error}><input type="email" /></Field>',
    exports: ["Field", "FieldError", "FieldLabel", "fieldLabelClass"],
  },
  {
    name: "filter-pill",
    description: "Toggle pill for one filter value, or an applied filter with a × to remove it",
    category: "primitives",
    files: ["primitives/filter-pill.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-url-filter", "icon-lib"],
    usage: `<FilterPill label="film" count={12} active={type === "film"} onClick={…} />`,
    exports: ["FilterPill"],
  },
  {
    name: "use-url-filter",
    description: "Hook that keeps a filter in the URL query, prerender safe",
    category: "hooks",
    files: ["hooks/use-url-filter.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "chrome-message",
    description: "Full-page status screen for 404s and errors, as a terminal command",
    category: "feedback",
    files: ["feedback/chrome-message.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage: `<ChromeMessage command="cat ./page" title="Page not found." note="it moved" action={…} />`,
    exports: ["ChromeMessage"],
  },
  {
    name: "page-loading",
    description: "Loading screen in CSS alone, that says more only when the wait runs long",
    category: "feedback",
    files: ["feedback/page-loading.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<PageLoading command="ls ./log" label="the log" steps={["reading entries"]} />`,
    exports: ["PageLoading"],
  },
  {
    name: "sect-head",
    description: "The $ command rule that opens a section, with meta on the right",
    category: "content",
    files: ["content/sect-head.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<SectHead cmd="ls ./work" meta="4 items" />`,
    exports: ["SectHead"],
  },
  {
    name: "doc-parts",
    description: "Long-form page pieces: doc labels, sections, serif heading, prose, Em, Strong",
    category: "content",
    files: ["content/doc-parts.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage: `<Section id="about"><DocLabel>about</DocLabel><DisplayH2>Title</DisplayH2><Prose>…</Prose></Section>`,
    exports: ["DisplayH2", "DocLabel", "Em", "Prose", "Section", "Strong"],
  },
  {
    name: "sidebar",
    description:
      "App navigation: a 56px icon rail, or labeled with groups, search and footer that folds back to the rail",
    category: "layout",
    files: ["layout/sidebar.tsx"],
    deps: ["@phosphor-icons/react", "motion"],
    registryDeps: ["motion-lib", "icon-lib", "nav-lib", "tooltip"],
    usage: `<Sidebar variant="labeled" groups={GROUPS} active="home" collapsible linkComponent={Link} />`,
    exports: ["Sidebar"],
  },
  {
    name: "mobile-nav",
    description: "Bottom bar with four destinations and More, which opens a sheet",
    category: "layout",
    files: ["layout/mobile-nav.tsx"],
    deps: ["@phosphor-icons/react", "motion"],
    registryDeps: ["sheet", "icon-tile", "motion-lib", "icon-lib", "nav-lib"],
    usage: `<MobileNav items={ITEMS} active="home" linkComponent={Link} className="md:hidden" />`,
    exports: ["MobileNav"],
  },
  {
    name: "bento-grid",
    description:
      "Dashboard tiles on the 12 column grid, each one a size container, entering in order",
    category: "layout",
    files: ["layout/bento-grid.tsx"],
    deps: ["motion"],
    registryDeps: ["reveal"],
    usage:
      "<BentoGrid><BentoItem colSpan={{ sm: 6, lg: 8 }}><Card>…</Card></BentoItem></BentoGrid>",
    exports: ["BentoGrid", "BentoItem"],
  },
  {
    name: "page-outline",
    description: "Sticky outline of the page's sections with a scrollspy, from 1100px up",
    category: "layout",
    files: ["layout/page-outline.tsx"],
    deps: ["motion"],
    registryDeps: ["diamond", "motion-lib"],
    usage: `<PageOutline items={SECTIONS} file="about.md" />`,
    exports: ["PageOutline"],
  },
];
