/**
 * Every installable item in the registry: what the CLI copies and installs, and
 * what the docs site lists. One source, so the two cannot drift.
 */

/**
 * The folders components live in. In a user project they all land in one
 * folder, so an import from one to another becomes a sibling import; the CLI
 * and the docs build that rewrite from this list.
 */
export const COMPONENT_FOLDERS = [
  "primitives",
  "layout",
  "content",
  "feedback",
  "motion",
  "data",
  "charts",
] as const;

export type RegistryCategory = (typeof COMPONENT_FOLDERS)[number] | "hooks" | "lib";

export interface RegistryComponent {
  name: string;
  description: string;
  category: RegistryCategory;
  files: string[];
  deps: string[];
  registryDeps: string[];
  /** One line of JSX showing the component in use. Every component has one; hooks and lib files do not. */
  usage?: string;
  /** What its own files export, for import lines. Checked against the files by a test. */
  exports?: string[];
}

export const COMPONENTS: RegistryComponent[] = [
  {
    name: "button",
    description: "Primary action button with 4 variants, icon sizes and a loading state",
    category: "primitives",
    files: ["primitives/button.tsx", "primitives/button-variants.ts"],
    deps: ["class-variance-authority", "@phosphor-icons/react", "@radix-ui/react-slot"],
    registryDeps: [],
    usage: `<Button variant="primary" size="md">ship it</Button>`,
    exports: ["Button", "buttonVariants"],
  },
  {
    name: "badge",
    description: "Status badge, solid/soft/outline across 6 semantic colors, with a dot or an icon",
    category: "primitives",
    files: ["primitives/badge.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["icon-lib"],
    usage: `<Badge variant="soft" color="success" dot>shipped</Badge>`,
    exports: ["Badge", "badgeVariants"],
  },
  {
    name: "avatar",
    description:
      "A person or a thing as an image over its initials, with a presence dot and a stacked group",
    category: "primitives",
    files: ["primitives/avatar.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["icon-lib"],
    usage: `<Avatar name="Anna Maria" src="/me.jpg" status="online" />`,
    exports: ["Avatar", "AvatarGroup", "avatarVariants"],
  },
  {
    name: "input",
    description: "Text input with default, search, and command (⌘K) variants",
    category: "primitives",
    files: ["primitives/input.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["kbd"],
    usage: `<Input variant="search" placeholder="search…" />`,
    exports: ["Input"],
  },
  {
    name: "card",
    description: "Content card, default/featured/terminal/data variants in three sizes",
    category: "primitives",
    files: ["primitives/card.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["diamond", "icon-lib"],
    usage:
      "<Card><CardHeader><CardLabel>post</CardLabel><CardMeta>2026</CardMeta></CardHeader><CardTitle>Title</CardTitle></Card>",
    exports: [
      "Card",
      "cardVariants",
      "CardHeader",
      "CardLabel",
      "CardMeta",
      "CardTitle",
      "CardDescription",
      "CardContent",
      "CardFooter",
      "CardComment",
      "CardTerminalBar",
      "CardTerminalBody",
    ],
  },
  {
    name: "dialog",
    description: "Modal dialog built on Radix UI with accessible close button",
    category: "primitives",
    files: ["primitives/dialog.tsx"],
    deps: ["@radix-ui/react-dialog", "@phosphor-icons/react"],
    registryDeps: ["diamond", "overlay-lib", "icon-lib"],
    usage:
      "<Dialog><DialogTrigger asChild><Button>open</Button></DialogTrigger><DialogContent><DialogTitle>Title</DialogTitle></DialogContent></Dialog>",
    exports: [
      "Dialog",
      "DialogClose",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogLabel",
      "DialogOverlay",
      "DialogPortal",
      "DialogTitle",
      "DialogTrigger",
    ],
  },
  {
    name: "dropdown",
    description: "Dropdown menu with items, checkboxes, radio groups and submenus",
    category: "primitives",
    files: ["primitives/dropdown.tsx"],
    deps: ["@radix-ui/react-dropdown-menu", "@phosphor-icons/react"],
    registryDeps: ["kbd", "overlay-lib"],
    usage:
      "<DropdownMenu><DropdownMenuTrigger asChild><Button>menu</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>item</DropdownMenuItem></DropdownMenuContent></DropdownMenu>",
    exports: [
      "DropdownMenu",
      "DropdownMenuCheckboxItem",
      "DropdownMenuContent",
      "DropdownMenuDestructiveItem",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuLabel",
      "DropdownMenuPortal",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuTrigger",
    ],
  },
  {
    name: "tooltip",
    description: "Hover tooltip with optional keyboard shortcut hint",
    category: "primitives",
    files: ["primitives/tooltip.tsx"],
    deps: ["@radix-ui/react-tooltip"],
    registryDeps: ["kbd", "overlay-lib"],
    usage:
      "<Tooltip><TooltipTrigger asChild><Button>save</Button></TooltipTrigger><TooltipContent>save <TooltipShortcut>⌘S</TooltipShortcut></TooltipContent></Tooltip>",
    exports: ["Tooltip", "TooltipContent", "TooltipProvider", "TooltipShortcut", "TooltipTrigger"],
  },
  {
    name: "tabs",
    description:
      "Editor file tabs, in place or as routes, with a travelling underline, a close button and a title bar variant",
    category: "primitives",
    files: ["primitives/tabs.tsx"],
    deps: ["@radix-ui/react-tabs", "@radix-ui/react-slot", "@phosphor-icons/react", "motion"],
    registryDeps: ["diamond", "motion-lib"],
    usage: `<Tabs defaultValue="a"><TabsList><TabsTrigger value="a">a.tsx</TabsTrigger></TabsList><TabsContent value="a">…</TabsContent></Tabs>`,
    exports: ["TabNav", "TabNavLink", "Tabs", "TabsContent", "TabsList", "TabsTrigger"],
  },
  {
    name: "status-bar",
    description: "Bottom status bar in the brand color, fixed or in your layout",
    category: "layout",
    files: ["layout/status-bar.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage:
      "<StatusBar left={<StatusBarItem>main</StatusBarItem>} right={<StatusBarItem>UTF-8</StatusBarItem>} />",
    exports: ["StatusBar", "StatusBarItem", "StatusBarSeparator", "statusBarVariants"],
  },
  {
    name: "top-nav",
    description: "Horizontal nav bar with logo, breadcrumb, and actions slots",
    category: "layout",
    files: ["layout/top-nav.tsx"],
    deps: [],
    registryDeps: [],
    usage: "<TopNav left={<TopNavLogo>…</TopNavLogo>} right={…} />",
    exports: [
      "TopNav",
      "TopNavBreadcrumb",
      "TopNavLink",
      "TopNavLogo",
      "TopNavLogoMark",
      "TopNavMenu",
      "TopNavSeparator",
    ],
  },
  {
    name: "skeleton",
    description: "Animated shimmer placeholder for loading states",
    category: "feedback",
    files: ["feedback/skeleton.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<Skeleton variant="line" delay={i * 0.06} />`,
    exports: ["Skeleton", "SkeletonText"],
  },
  {
    name: "toast",
    description: "Toast notifications via Sonner, styled with entrepta tokens",
    category: "feedback",
    files: ["feedback/toast.tsx"],
    deps: ["sonner", "@phosphor-icons/react"],
    registryDeps: ["overlay-lib"],
    usage: `<Toaster /> then toast.success("saved")`,
    exports: ["Toaster", "toast"],
  },
  {
    name: "use-command-palette",
    description: "Hook that wires the ⌘K global shortcut to open/close the command palette",
    category: "hooks",
    files: ["hooks/use-command-palette.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-copy",
    description: "Hook that copies text and reports copied or failed, then settles back",
    category: "hooks",
    files: ["hooks/use-copy.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-mode",
    description: "Hook that manages dark/light mode with localStorage persistence",
    category: "hooks",
    files: ["hooks/use-mode.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-theme",
    description: "Hook that manages theme + dark/light mode with localStorage persistence",
    category: "hooks",
    files: ["hooks/use-theme.ts"],
    deps: [],
    registryDeps: ["use-mode"],
  },
  {
    name: "theme-switcher",
    description: "Floating theme + mode picker with no-flash ThemeScript helper",
    category: "layout",
    files: ["layout/theme-switcher.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-theme", "overlay-lib"],
    usage: "<ThemeSwitcher themes={THEMES} /> with <ThemeScript /> in <head>",
    exports: ["ThemeScript", "ThemeSwitcher"],
  },
  {
    name: "mode-toggle",
    description: "Dark/light only toggle, inline or floating, with no-flash ModeScript helper",
    category: "layout",
    files: ["layout/mode-toggle.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["use-mode"],
    usage: "<ModeToggle /> with <ModeScript /> in <head>",
    exports: ["ModeScript", "ModeToggle"],
  },
  {
    name: "command-palette",
    description: "⌘K command palette built on cmdk with groups, icons, and shortcuts",
    category: "feedback",
    files: ["feedback/command-palette.tsx"],
    deps: ["cmdk", "@radix-ui/react-dialog", "@phosphor-icons/react"],
    registryDeps: ["use-command-palette", "kbd", "overlay-lib"],
    usage:
      "<CommandDialog open={open} onOpenChange={setOpen}><Command><CommandInput /><CommandList>…</CommandList></Command></CommandDialog>",
    exports: [
      "Command",
      "CommandDialog",
      "CommandEmpty",
      "CommandFoot",
      "CommandGroup",
      "CommandInput",
      "CommandItem",
      "CommandList",
      "CommandSeparator",
    ],
  },
  {
    name: "diamond",
    description: "The ◆ brand mark placed before a label, hidden from screen readers",
    category: "content",
    files: ["content/diamond.tsx"],
    deps: [],
    registryDeps: [],
    usage: "<Diamond size={10} />",
    exports: ["Diamond"],
  },
  {
    name: "code-block",
    description: "Code container with macOS chrome, language label and a copy-to-clipboard button",
    category: "content",
    files: ["content/code-block.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-copy"],
    usage: `<CodeBlock code="npm run dev" language="bash" variant="terminal" />`,
    exports: ["CodeBlock"],
  },
  {
    name: "icon-lib",
    description: "An icon prop that takes a Phosphor component or an element",
    category: "lib",
    files: ["lib/icon.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: [],
  },
  {
    name: "overlay-lib",
    description: "The shared overlay surface, menu row, label and separator classes",
    category: "lib",
    files: ["lib/overlay.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "motion-lib",
    description: "Shared motion values: the ease-out curve, the viewport rule and the stagger cap",
    category: "lib",
    files: ["lib/motion.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "color-contrast",
    description: "WCAG contrast math: parse colors, flatten translucent layers, measure the ratio",
    category: "lib",
    files: ["lib/color-contrast.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "reveal",
    description: "Entrance that rises and fades in once on screen, with a capped list stagger",
    category: "motion",
    files: ["motion/reveal.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
    usage: "<Reveal index={i}><Card>…</Card></Reveal>",
    exports: ["Reveal", "useReveal"],
  },
  {
    name: "type-in",
    description: "Text that assembles piece by piece, with the full sentence always in the DOM",
    category: "motion",
    files: ["motion/type-in.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
    usage: `<TypeIn as="h1" text="Build with entrepta." emphasis="entrepta" />`,
    exports: ["TypeIn"],
  },
  {
    name: "rolling-number",
    description: "Odometer counter that rolls into place and turns once on hover",
    category: "motion",
    files: ["motion/rolling-number.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
    usage: "<RollingNumber value={128} height={44} />",
    exports: ["RollingNumber", "useRollOnHover"],
  },
  {
    name: "spotlight",
    description: "Brand glow that trails the cursor across a card on a spring",
    category: "motion",
    files: ["motion/spotlight.tsx"],
    deps: ["motion"],
    registryDeps: [],
    usage:
      "const { onMouseMove, spotlight } = useSpotlight(); <Card onMouseMove={onMouseMove}><Spotlight {...spotlight} />…</Card>",
    exports: ["Spotlight", "useSpotlight"],
  },
  {
    name: "arrow-link",
    description: "Text link with a traveling arrow and a brand rule that wipes in",
    category: "motion",
    files: ["motion/arrow-link.tsx"],
    deps: ["@phosphor-icons/react", "@radix-ui/react-slot"],
    registryDeps: [],
    usage: `<ArrowLink href="/docs">read the docs</ArrowLink>`,
    exports: ["ArrowAffordance", "ArrowLink"],
  },
  {
    name: "switch",
    description: "On/off switch over a native checkbox, with an optional label",
    category: "primitives",
    files: ["primitives/switch.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<Switch label="notifications" />`,
    exports: ["Switch"],
  },
  {
    name: "kbd",
    description: "A key or a shortcut, as a chip or plain, that turns brand in a highlighted row",
    category: "primitives",
    files: ["primitives/kbd.tsx"],
    deps: [],
    registryDeps: [],
    usage: "<Kbd>⌘K</Kbd>",
    exports: ["Kbd"],
  },
  {
    name: "checkbox",
    description: "Checkbox over a native input, with a label, a description and a mixed state",
    category: "primitives",
    files: ["primitives/checkbox.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<Checkbox label="button" description="4 variants" defaultChecked />`,
    exports: ["Checkbox"],
  },
  {
    name: "textarea",
    description: "Multi-line text field in sans, with an error state",
    category: "primitives",
    files: ["primitives/textarea.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage: `<Textarea placeholder="// your message" />`,
    exports: ["Textarea", "textareaVariants"],
  },
  {
    name: "field",
    description: "Label, control and error or hint, wired together for screen readers",
    category: "primitives",
    files: ["primitives/field.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["diamond", "icon-lib"],
    usage: '<Field id="email" label="email" error={error}><input type="email" /></Field>',
    exports: ["Field", "FieldError", "FieldLabel"],
  },
  {
    name: "filter-pill",
    description: "Toggle pill for one filter value, with an optional count and icon",
    category: "primitives",
    files: ["primitives/filter-pill.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-url-filter"],
    usage: `<FilterPill label="film" count={12} active={type === "film"} onClick={…} />`,
    exports: ["FilterPill"],
  },
  {
    name: "use-url-filter",
    description: "Hook that keeps a filter in the URL query, prerender safe",
    category: "hooks",
    files: ["hooks/use-url-filter.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "chrome-message",
    description: "Full-page status screen for 404s and errors, as a terminal command",
    category: "feedback",
    files: ["feedback/chrome-message.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage: `<ChromeMessage command="cat ./page" title="Page not found." note="it moved" action={…} />`,
    exports: ["ChromeMessage"],
  },
  {
    name: "page-loading",
    description: "Loading screen in CSS alone, that says more only when the wait runs long",
    category: "feedback",
    files: ["feedback/page-loading.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<PageLoading command="ls ./log" label="the log" steps={["reading entries"]} />`,
    exports: ["PageLoading"],
  },
  {
    name: "sect-head",
    description: "The $ command rule that opens a section, with meta on the right",
    category: "content",
    files: ["content/sect-head.tsx"],
    deps: [],
    registryDeps: [],
    usage: `<SectHead cmd="ls ./work" meta="4 items" />`,
    exports: ["SectHead"],
  },
  {
    name: "doc-parts",
    description: "Long-form page pieces: doc labels, sections, serif heading, prose, Em, Strong",
    category: "content",
    files: ["content/doc-parts.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
    usage: `<Section id="about"><DocLabel>about</DocLabel><DisplayH2>Title</DisplayH2><Prose>…</Prose></Section>`,
    exports: ["DisplayH2", "DocLabel", "Em", "Prose", "Section", "Strong"],
  },
  {
    name: "sidebar",
    description: "56px icon rail with a diamond that travels to the active item",
    category: "layout",
    files: ["layout/sidebar.tsx"],
    deps: ["@phosphor-icons/react", "motion"],
    registryDeps: ["motion-lib"],
    usage: `<Sidebar items={ITEMS} active="home" linkComponent={Link} />`,
    exports: ["Sidebar"],
  },
  {
    name: "page-outline",
    description: "Sticky outline of the page's sections with a scrollspy, from 1100px up",
    category: "layout",
    files: ["layout/page-outline.tsx"],
    deps: ["motion"],
    registryDeps: ["diamond", "motion-lib"],
    usage: `<PageOutline items={SECTIONS} file="about.md" />`,
    exports: ["PageOutline"],
  },
];
