/**
 * Every installable item in the registry: what the CLI copies and installs, and
 * what the docs site lists. One source, so the two cannot drift.
 */

export interface RegistryComponent {
  name: string;
  description: string;
  category: "primitives" | "layout" | "content" | "feedback" | "motion" | "hooks" | "lib";
  files: string[];
  deps: string[];
  registryDeps: string[];
}

export const COMPONENTS: RegistryComponent[] = [
  {
    name: "button",
    description: "Primary action button with 4 variants and loading state",
    category: "primitives",
    files: ["primitives/button.tsx", "primitives/button-variants.ts"],
    deps: ["class-variance-authority", "@phosphor-icons/react", "@radix-ui/react-slot"],
    registryDeps: [],
  },
  {
    name: "badge",
    description: "Status badge, solid/soft/outline across 6 semantic colors",
    category: "primitives",
    files: ["primitives/badge.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "input",
    description: "Text input with default, search, and command (⌘K) variants",
    category: "primitives",
    files: ["primitives/input.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: [],
  },
  {
    name: "card",
    description: "Content card, default/featured/terminal/data variants in three sizes",
    category: "primitives",
    files: ["primitives/card.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: ["diamond"],
  },
  {
    name: "dialog",
    description: "Modal dialog built on Radix UI with accessible close button",
    category: "primitives",
    files: ["primitives/dialog.tsx"],
    deps: ["@radix-ui/react-dialog", "@phosphor-icons/react"],
    registryDeps: ["diamond"],
  },
  {
    name: "dropdown",
    description: "Dropdown menu with items, checkboxes, radio groups and submenus",
    category: "primitives",
    files: ["primitives/dropdown.tsx"],
    deps: ["@radix-ui/react-dropdown-menu", "@phosphor-icons/react"],
    registryDeps: [],
  },
  {
    name: "tooltip",
    description: "Hover tooltip with optional keyboard shortcut hint",
    category: "primitives",
    files: ["primitives/tooltip.tsx"],
    deps: ["@radix-ui/react-tooltip"],
    registryDeps: [],
  },
  {
    name: "tabs",
    description:
      "Editor file tabs, in place or as routes, with a travelling underline and a close button",
    category: "primitives",
    files: ["primitives/tabs.tsx"],
    deps: ["@radix-ui/react-tabs", "@radix-ui/react-slot", "@phosphor-icons/react", "motion"],
    registryDeps: ["diamond", "motion-lib"],
  },
  {
    name: "status-bar",
    description: "Bottom status bar in the brand color, fixed or in your layout",
    category: "layout",
    files: ["layout/status-bar.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "top-nav",
    description: "Horizontal nav bar with logo, breadcrumb, and actions slots",
    category: "layout",
    files: ["layout/top-nav.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "skeleton",
    description: "Animated shimmer placeholder for loading states",
    category: "feedback",
    files: ["feedback/skeleton.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "toast",
    description: "Toast notifications via Sonner, styled with entrepta tokens",
    category: "feedback",
    files: ["feedback/toast.tsx"],
    deps: ["sonner"],
    registryDeps: [],
  },
  {
    name: "use-command-palette",
    description: "Hook that wires the ⌘K global shortcut to open/close the command palette",
    category: "hooks",
    files: ["hooks/use-command-palette.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-mode",
    description: "Hook that manages dark/light mode with localStorage persistence",
    category: "hooks",
    files: ["hooks/use-mode.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "use-theme",
    description: "Hook that manages theme + dark/light mode with localStorage persistence",
    category: "hooks",
    files: ["hooks/use-theme.ts"],
    deps: [],
    registryDeps: ["use-mode"],
  },
  {
    name: "theme-switcher",
    description: "Floating theme + mode picker with no-flash ThemeScript helper",
    category: "layout",
    files: ["layout/theme-switcher.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: ["use-theme", "diamond"],
  },
  {
    name: "mode-toggle",
    description: "Dark/light only toggle, inline or floating, with no-flash ModeScript helper",
    category: "layout",
    files: ["layout/mode-toggle.tsx"],
    deps: ["class-variance-authority", "@phosphor-icons/react"],
    registryDeps: ["use-mode"],
  },
  {
    name: "command-palette",
    description: "⌘K command palette built on cmdk with groups, icons, and shortcuts",
    category: "feedback",
    files: ["feedback/command-palette.tsx"],
    deps: ["cmdk", "@radix-ui/react-dialog", "@phosphor-icons/react"],
    registryDeps: ["use-command-palette"],
  },
  {
    name: "diamond",
    description: "The ◆ brand mark placed before a label, hidden from screen readers",
    category: "content",
    files: ["content/diamond.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "code-block",
    description: "Code container with macOS chrome, language label and a copy-to-clipboard button",
    category: "content",
    files: ["content/code-block.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: [],
  },
  {
    name: "motion-lib",
    description: "Shared motion values: the ease-out curve, the viewport rule and the stagger cap",
    category: "lib",
    files: ["lib/motion.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "color-contrast",
    description: "WCAG contrast math: parse colors, flatten translucent layers, measure the ratio",
    category: "lib",
    files: ["lib/color-contrast.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "reveal",
    description: "Entrance that rises and fades in once on screen, with a capped list stagger",
    category: "motion",
    files: ["motion/reveal.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
  },
  {
    name: "type-in",
    description: "Text that assembles piece by piece, with the full sentence always in the DOM",
    category: "motion",
    files: ["motion/type-in.tsx"],
    deps: ["motion"],
    registryDeps: ["motion-lib"],
  },
  {
    name: "rolling-number",
    description: "Odometer counter that rolls into place and turns once on hover",
    category: "motion",
    files: ["motion/rolling-number.tsx"],
    deps: ["motion"],
    registryDeps: [],
  },
  {
    name: "spotlight",
    description: "Brand glow that trails the cursor across a card on a spring",
    category: "motion",
    files: ["motion/spotlight.tsx"],
    deps: ["motion"],
    registryDeps: [],
  },
  {
    name: "arrow-link",
    description: "Text link with a traveling arrow and a brand rule that wipes in",
    category: "motion",
    files: ["motion/arrow-link.tsx"],
    deps: ["@phosphor-icons/react", "@radix-ui/react-slot"],
    registryDeps: [],
  },
  {
    name: "switch",
    description: "On/off switch over a native checkbox, with an optional label",
    category: "primitives",
    files: ["primitives/switch.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "textarea",
    description: "Multi-line text field in sans, with an error state",
    category: "primitives",
    files: ["primitives/textarea.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "field",
    description: "Label, control and error or hint, wired together for screen readers",
    category: "primitives",
    files: ["primitives/field.tsx"],
    deps: [],
    registryDeps: ["diamond"],
  },
  {
    name: "filter-pill",
    description: "Toggle pill for one filter value, with an optional count and icon",
    category: "primitives",
    files: ["primitives/filter-pill.tsx"],
    deps: ["@phosphor-icons/react"],
    registryDeps: [],
  },
  {
    name: "use-url-filter",
    description: "Hook that keeps a filter in the URL query, prerender safe",
    category: "hooks",
    files: ["hooks/use-url-filter.ts"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "chrome-message",
    description: "Full-page status screen for 404s and errors, as a terminal command",
    category: "feedback",
    files: ["feedback/chrome-message.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "page-loading",
    description: "Loading screen in CSS alone, that says more only when the wait runs long",
    category: "feedback",
    files: ["feedback/page-loading.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "sect-head",
    description: "The $ command rule that opens a section, with meta on the right",
    category: "content",
    files: ["content/sect-head.tsx"],
    deps: [],
    registryDeps: [],
  },
  {
    name: "doc-parts",
    description: "Long-form page pieces: doc labels, sections, serif heading, prose, Em, Strong",
    category: "content",
    files: ["content/doc-parts.tsx"],
    deps: ["class-variance-authority"],
    registryDeps: [],
  },
  {
    name: "sidebar",
    description: "56px icon rail with a diamond that travels to the active item",
    category: "layout",
    files: ["layout/sidebar.tsx"],
    deps: ["@phosphor-icons/react", "motion"],
    registryDeps: ["motion-lib"],
  },
  {
    name: "page-outline",
    description: "Sticky outline of the page's sections with a scrollspy, from 1100px up",
    category: "layout",
    files: ["layout/page-outline.tsx"],
    deps: ["motion"],
    registryDeps: ["diamond", "motion-lib"],
  },
  {
    name: "titlebar",
    description: "40px editor title bar with window dots, a tab row and meta",
    category: "layout",
    files: ["layout/titlebar.tsx"],
    deps: [],
    registryDeps: [],
  },
];
